name: Build and Deploy
on: # 监听 main 分支上的 push 事件
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 构建环境使用 ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1  
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v16.16.0'

      - name: Install and Build # 下载依赖 打包项目
        run: |
          yarn
          yarn build

      - name: Deploy # 将打包内容发布到 github page
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:  # 自定义环境变量
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # secret
          BRANCH: gh-pages  # 这个是存放打包后的分支
          FOLDER: ./docs/.vuepress/dist  # 默认 vue 项目打包输出目录是 dist, 自行修改
          REPOSITORY_NAME: jianping5/jianping5.github.io # 这是我的 github page 仓库
          TARGET_FOLDER: / # 打包的文件将放到静态服务器 / 目录下
